-- Insert sample vegetarian recipes
INSERT INTO recipes (title, description, diet_type, meal_type, access_level, calories, protein, carbs, fats, ingredients, instructions, tags, image_url, prep_time, cook_time, difficulty) VALUES
('Greek Yogurt Parfait', 'A protein-packed breakfast with layers of Greek yogurt, fresh berries, and crunchy granola', 'veg', 'breakfast', 'guest', 310, 24, 38, 8, '[{"name": "Greek yogurt", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Mixed berries", "amount": 100, "unit": "g", "substitutable": true}, {"name": "Granola", "amount": 30, "unit": "g", "substitutable": true}]', '["Mix Greek yogurt with a touch of honey", "Layer yogurt in a glass", "Add fresh berries on top", "Sprinkle with granola", "Serve immediately"]', ARRAY['High Protein', 'Quick', 'Breakfast'], 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800', 5, 0, 'Easy'),

('Paneer & Quinoa Bowl', 'Nutritious bowl with grilled paneer, quinoa, and colorful vegetables', 'veg', 'lunch', 'logged_in', 485, 42, 52, 14, '[{"name": "Paneer cubes", "amount": 150, "unit": "g", "substitutable": true}, {"name": "Quinoa", "amount": 100, "unit": "g", "substitutable": false}, {"name": "Mixed vegetables", "amount": 150, "unit": "g", "substitutable": true}, {"name": "Olive oil", "amount": 1, "unit": "tbsp", "substitutable": false}]', '["Cook quinoa according to package instructions", "Grill paneer cubes with spices", "Sauté mixed vegetables", "Combine all in a bowl", "Season with salt, pepper and lemon", "Serve hot"]', ARRAY['High Protein', 'Vegetarian', 'Lunch'], 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800', 10, 20, 'Medium'),

('Tofu Vegetable Stir-Fry', 'Crispy tofu paired with colorful roasted vegetables', 'veg', 'dinner', 'guest', 420, 28, 36, 18, '[{"name": "Firm tofu", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Bell peppers", "amount": 150, "unit": "g", "substitutable": true}, {"name": "Zucchini", "amount": 100, "unit": "g", "substitutable": true}, {"name": "Soy sauce", "amount": 2, "unit": "tbsp", "substitutable": false}]', '["Press and cube tofu", "Marinate tofu with soy sauce and spices", "Stir-fry vegetables at high heat", "Add tofu and cook until golden", "Serve hot with rice or noodles"]', ARRAY['Vegan', 'Dinner', 'Healthy'], 'https://images.unsplash.com/photo-1540914124281-342587941389?w=800', 15, 25, 'Easy'),

('Moong Dal Chilla', 'Protein-rich Indian savory pancakes made from split moong dal', 'veg', 'breakfast', 'guest', 320, 24, 42, 6, '[{"name": "Moong dal", "amount": 150, "unit": "g", "substitutable": false}, {"name": "Onions", "amount": 50, "unit": "g", "substitutable": true}, {"name": "Green chilies", "amount": 2, "unit": "pcs", "substitutable": true}, {"name": "Ginger", "amount": 1, "unit": "tsp", "substitutable": false}]', '["Soak moong dal for 4 hours", "Grind into smooth batter", "Add chopped onions, chilies, and spices", "Pour on hot griddle", "Cook both sides until golden", "Serve with chutney"]', ARRAY['High Protein', 'Indian', 'Breakfast'], 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800', 10, 15, 'Medium'),

('Palak Paneer', 'Classic Indian dish with spinach and cottage cheese', 'veg', 'dinner', 'logged_in', 510, 32, 28, 28, '[{"name": "Paneer", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Spinach", "amount": 300, "unit": "g", "substitutable": false}, {"name": "Cream", "amount": 50, "unit": "ml", "substitutable": true}, {"name": "Tomatoes", "amount": 100, "unit": "g", "substitutable": false}]', '["Blanch spinach and puree", "Sauté onions, ginger, garlic", "Add tomatoes and cook", "Add spinach puree", "Add paneer cubes", "Finish with cream and serve"]', ARRAY['High Protein', 'Indian', 'Dinner'], 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800', 15, 30, 'Medium'),

-- Insert sample non-vegetarian recipes
('Grilled Chicken & Quinoa Bowl', 'Lean grilled chicken with quinoa and fresh vegetables', 'non_veg', 'lunch', 'guest', 485, 42, 48, 12, '[{"name": "Chicken breast", "amount": 150, "unit": "g", "substitutable": false}, {"name": "Quinoa", "amount": 100, "unit": "g", "substitutable": false}, {"name": "Mixed vegetables", "amount": 150, "unit": "g", "substitutable": true}]', '["Cook quinoa as per instructions", "Season and grill chicken", "Sauté vegetables", "Slice grilled chicken", "Arrange in bowl and serve"]', ARRAY['High Protein', 'Lunch', 'Healthy'], 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800', 10, 20, 'Easy'),

('Salmon with Roasted Vegetables', 'Omega-3 rich salmon with colorful roasted veggies', 'non_veg', 'dinner', 'subscribed', 520, 38, 32, 24, '[{"name": "Salmon fillet", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Broccoli", "amount": 150, "unit": "g", "substitutable": true}, {"name": "Bell peppers", "amount": 100, "unit": "g", "substitutable": true}, {"name": "Olive oil", "amount": 1, "unit": "tbsp", "substitutable": false}]', '["Preheat oven to 200°C", "Season salmon with lemon and herbs", "Toss vegetables with olive oil", "Bake salmon for 15 minutes", "Roast vegetables for 20 minutes", "Serve together"]', ARRAY['High Protein', 'Dinner', 'Premium'], 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 10, 25, 'Medium'),

('Chicken Biryani Bowl', 'Fragrant Indian rice dish with tender chicken', 'non_veg', 'lunch', 'logged_in', 520, 38, 62, 14, '[{"name": "Chicken pieces", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Basmati rice", "amount": 100, "unit": "g", "substitutable": false}, {"name": "Yogurt", "amount": 50, "unit": "g", "substitutable": false}, {"name": "Biryani spices", "amount": 2, "unit": "tbsp", "substitutable": false}]', '["Marinate chicken with yogurt and spices", "Cook rice 70% done", "Layer chicken and rice", "Cook on low heat (dum)", "Garnish with fried onions", "Serve with raita"]', ARRAY['Indian', 'Lunch', 'Flavorful'], 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800', 20, 40, 'Hard'),

('Egg White Omelette', 'Light and protein-packed breakfast omelette', 'non_veg', 'breakfast', 'guest', 250, 28, 8, 12, '[{"name": "Egg whites", "amount": 6, "unit": "pcs", "substitutable": false}, {"name": "Spinach", "amount": 50, "unit": "g", "substitutable": true}, {"name": "Mushrooms", "amount": 50, "unit": "g", "substitutable": true}, {"name": "Cheese", "amount": 30, "unit": "g", "substitutable": true}]', '["Whisk egg whites", "Sauté vegetables", "Pour egg whites in pan", "Add vegetables and cheese", "Fold and cook", "Serve hot"]', ARRAY['High Protein', 'Breakfast', 'Low Carb'], 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800', 5, 10, 'Easy'),

('Butter Chicken', 'Creamy and flavorful Indian chicken curry', 'non_veg', 'dinner', 'subscribed', 560, 36, 42, 24, '[{"name": "Chicken", "amount": 250, "unit": "g", "substitutable": false}, {"name": "Tomatoes", "amount": 200, "unit": "g", "substitutable": false}, {"name": "Cream", "amount": 100, "unit": "ml", "substitutable": false}, {"name": "Butter", "amount": 30, "unit": "g", "substitutable": false}]', '["Marinate chicken with spices", "Grill or bake chicken", "Prepare tomato gravy", "Add cream and butter", "Add chicken to gravy", "Simmer and serve with naan"]', ARRAY['Indian', 'Dinner', 'Premium'], 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800', 20, 35, 'Medium');
