// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaqjnyjkosefosbncwki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthcWpueWprb3NlZm9zYm5jd2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzQwNjIsImV4cCI6MjA3ODIxMDA2Mn0.u4bFz223JdDpnWUiIm25T0ddNHX467LpVgOgHrcsqdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});